struct VertexOutputType {
    float4 position: POSITION;
    float2 texCoord: TEXCOORD0;
    float3 normal: TEXCOORD1;
    float3 depth: TEXCOORD2;
};

struct FragmentOutputType {
    float4 color  :COLOR0;
    float4 normal :COLOR1;
    float4 depth  :COLOR2;
    float4 light  :COLOR3;
};

float3 encode(float3 n) {
    n = normalize(n);
    n.xyz = 0.5f * (n.xyz + 1.0f);
    return n;
}

float3 decode(float4 enc) {
    return (2.0f * enc.xyz - 1.0f);
}

// simple material properties
// to do with material id and multiple material model
const uniform float3 ambient = float3(0, 0, 0);
const uniform float specular_intensity = 0;
const uniform float specular_power = 0;

FragmentOutputType FragmentProgram(VertexOutputType input,
				                   uniform sampler2D diffuseMap: TEX0) {    
    FragmentOutputType output;
    // not using specular map now

    output.color = tex2D(diffuseMap, input.texCoord);
    output.color.w = specular_intensity;

    output.normal.xyz = encode(input.normal);
    output.normal.w = specular_power;

    output.depth.r = input.depth.x / input.depth.y;
    output.depth.g = input.depth.z;

    output.light = float4(ambient, 0);

    return output;
}