struct VertexOutputType {
    float4 position: POSITION;
};

struct FragmentOutputType {
    float4 color  :COLOR0;
    float4 normal :COLOR1;
    float4 depth  :COLOR2;
    float4 light  :COLOR3;
};

FragmentOutputType FragmentProgram(VertexOutputType input) {    
    FragmentOutputType output;

    output.color = 0.f;
    output.normal.xyz = 0.5f;
    output.normal.w = 0.0f;
    output.depth = 1.0f;
    output.light = 0.f;
    return output;
}